<script>
  const GITHUB_API_URL = "https://api.github.com/repos/BDEP-SDT/dados-tecnicos/dispatches";

  document.getElementById("formulario").addEventListener("submit", async (e) => {
    e.preventDefault();

    const dados = {
      nome: document.getElementById("nome").value,
      email: document.getElementById("email").value,
      descricao: document.getElementById("descricao").value,
    };

    const response = await fetch(GITHUB_API_URL, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        event_type: "novo_envio",
        client_payload: dados
      }),
    });

    if (response.ok) {
      document.getElementById("mensagem").textContent = "✅ Envio registrado! Aguarde processamento.";
    } else {
      document.getElementById("mensagem").textContent = "❌ Falha no envio. Verifique o console.";
      console.error(await response.text());
    }
  });
</script>
