name: Salvar envio do formulário

on:
  workflow_dispatch:
    inputs:
      nome:
        description: "Nome do remetente"
        required: true
      email:
        description: "E-mail"
        required: true
      descricao:
        description: "Descrição"
        required: true

jobs:
  salvar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Adicionar dados ao arquivo
        run: |
          mkdir -p dados
          FILE=dados/envios.json
          if [ ! -f "$FILE" ]; then
            echo "[]" > $FILE
          fi
          jq --arg nome "${{ github.event.inputs.nome }}" \
             --arg email "${{ github.event.inputs.email }}" \
             --arg descricao "${{ github.event.inputs.descricao }}" \
             '. += [{"nome": $nome, "email": $email, "descricao": $descricao, "data": "'$(date -u)'"}]' $FILE > tmp.json
          mv tmp.json $FILE

      - name: Commit e push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add dados/envios.json
          git commit -m "Novo envio via formulário"
          git push
