name: Salvar envio de formulário

on:
  repository_dispatch:
    types: [novo_envio]

jobs:
  salvar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Adicionar dados no arquivo
        run: |
          echo "Adicionando dados recebidos..."
          mkdir -p dados
          arquivo="dados/envios.json"
          payload=$(jq -n --arg nome "${{ github.event.client_payload.nome }}" \
                         --arg email "${{ github.event.client_payload.email }}" \
                         --arg descricao "${{ github.event.client_payload.descricao }}" \
                         '{nome: $nome, email: $email, descricao: $descricao, data: now | strftime("%Y-%m-%d %H:%M:%S")}')
          if [ -f "$arquivo" ]; then
            jq ". += [$payload]" "$arquivo" > temp.json && mv temp.json "$arquivo"
          else
            echo "[$payload]" > "$arquivo"
          fi

      - name: Commit e Push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "📩 Novo envio via formulário"
          file_pattern: dados/envios.json
          branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.BDEP_TOKEN }}
