name: Salvar Envio de Formulário

on:
  repository_dispatch:
    types: [novo_envio]

jobs:
  salvar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Criar pasta de dados
        run: mkdir -p data

      - name: Criar JSON com dados recebidos
        run: |
          echo '${{ toJson(github.event.client_payload) }}' > data/envio-${{ github.run_id }}.json

      - name: Fazer commit e push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/
          git commit -m "Novo envio via formulário"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.BDEP_TOKEN }}
